version: "3"
networks:
  expense:  # docker network create expense
volumes:
  mysql:    #docker volume create mysql

services:
  mysql:
    image: promptforai/mysql:v1
    networks:
      - expense
    volumes:
      - mysql:/var/lib/mysql
    container_name: mysql

  backend:
    image: promptforai/backend:v1
    networks:
      - expense
    command: sh -c "sleep 5 && node /opt/app/index.sh"
    container_name: backend
    depends_on:
      - mysql

  frontend:
    image: promptforai/frontend:v1
    networks:
      - expense
    container_name: frontend
    depends_on:
      - backend



